version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:22.9.0
    working_directory: ~/app

jobs:
  build:
    executor: node-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-deps-{{ checksum "package-lock.json" }}
            - node-deps-

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: node-deps-{{ checksum "package-lock.json" }}

      - run:
          name: Build project
          command: npm run build

workflows:
  version: 2
  vite-build:
    jobs:
      - build