"use client"

import { Button } from "@/components/ui/button"
import { X, MapPin, Download, Share2, Edit3 } from "lucide-react"
import { MarkdownOutput } from "./MarkdownOutput"

interface ItineraryPopupProps {
    isOpen: boolean
    onClose: () => void
    content: string
}

export default function ItineraryPopup({ isOpen, onClose, content }: ItineraryPopupProps) {
    if (!isOpen) return null

    return (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
            <div className="bg-gray-900 rounded-2xl w-full max-w-4xl max-h-[90vh] overflow-hidden border border-gray-800">
                {/* Header */}
                <div className="flex items-center justify-between p-6 border-b border-gray-800">
                    <div>
                        <h2 className="text-2xl font-bold text-white mb-1">Your Perfect Itinerary</h2>
                        <div className="flex items-center space-x-4 text-gray-400">
                            <span className="flex items-center space-x-1">
                                <MapPin className="h-4 w-4" />
                                <span>Generated Itinerary</span>
                            </span>
                        </div>
                    </div>
                    <div className="flex items-center space-x-2">
                        <Button variant="outline" size="sm" className="border-gray-700 text-white hover:bg-gray-800">
                            <Download className="h-4 w-4 mr-2" />
                            Export
                        </Button>
                        <Button variant="outline" size="sm" className="border-gray-700 text-white hover:bg-gray-800">
                            <Share2 className="h-4 w-4 mr-2" />
                            Share
                        </Button>
                        <Button variant="outline" size="sm" className="border-gray-700 text-white hover:bg-gray-800">
                            <Edit3 className="h-4 w-4 mr-2" />
                            Edit
                        </Button>
                        <Button
                            variant="ghost"
                            size="sm"
                            onClick={onClose}
                            className="text-gray-400 hover:text-white hover:bg-gray-800"
                        >
                            <X className="h-5 w-5" />
                        </Button>
                    </div>
                </div>

                {/* Main Content */}
                <div className="overflow-y-auto p-6 max-h-[calc(90vh-180px)]">
                    <div className="prose prose-invert max-w-none">
                        <MarkdownOutput markdownText={content} />
                    </div>
                </div>

                {/* Footer */}
                <div className="border-t border-gray-800 p-4 bg-gray-900">
                    <div className="flex items-center justify-between">
                        <div className="text-sm text-gray-400">Generated by Tabi.ai • Personalized for your preferences</div>
                        <Button className="bg-blue-600 hover:bg-blue-700" onClick={onClose}>Close</Button>
                    </div>
                </div>
            </div>
        </div>
    )
}